apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-execution-platform
  template:
    metadata:
      labels:
        app: code-execution-platform
    spec:
      containers:
      - name: web
        image: code-execution-platform:latest
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: code-execution-worker
  template:
    metadata:
      labels:
        app: code-execution-worker
    spec:
      containers:
      - name: worker
        image: code-execution-worker:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: code-execution-service
spec:
  selector:
    app: code-execution-platform
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379 